theme = "apollo"
taxonomies = [{ name = "tags" }]
base_url = "https://hazell.dev"
title="hazell.dev"
compile_sass = true
build_search_index = false
minify_html = true

[markdown]
highlight_code = true

[extra]
toc = true
use_cdn = false
theme = "toggle"
comment = false
fancy_code = true
dynamic_note = true
mathjax = true
mathjax_dollar_inline_enable = true

socials = [
    { name = "github", url = "https://github.com/lewishazell", icon = "github" }
]

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/portfolio", url = "/portfolio", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    { name = "/tags", url = "/tags", weight = 4 }
]
